name: Build

on: push

jobs:
  build:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker://pandoc/latex:latest
        with:
          args: resume.md -s -o resume.pdf
      - uses: docker://pandoc/latex:latest
        with:
          args: coverletter.md -s -s coverletter.pdf

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            resume.pdf
            coverletter.pdf
